Repository y casos de usos
gibmyx/laravelOnBoarding pull request #1
Opened 2024-09-16 21:06 UTC by buuu-u

finalizado repository y casos de usos

2024-09-17 13:11 UTC, gibmyx requested changes
Tembien tienes que agregar los tipeos a las variables de entradas de las funciones.

2024-09-17 13:11 UTC, gibmyx commented on app/Http/Controllers/PeopleController.php
> +        dd($useCase);
Dejaste un DD @buuu-u

2024-09-17 13:11 UTC, gibmyx commented on app/Repository/PeopleRepository.php
> +    }
Generalmente el destroy retorna un valor bool. igualmente puedes indicar que no vas a retornar nada y en el tipo de retorno indicar void que es para las funciones que no retorna nada.

2024-09-17 13:11 UTC, gibmyx commented on app/UseCase/EliminarPeople.php
> +    }
igual aqui, se te olvido el tipo de retorno.

2024-09-17 15:39 UTC, buuu-u commented
Cambios actualizados

2024-09-18 13:27 UTC, gibmyx approved these changes

2024-09-18 13:27 UTC, merged